version: '3.1'

services:

  acal_v4_db:
    image: mongo:latest
    container_name: acal_v4_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - acal-v4-network

networks:
  acal-v4-network:
    driver: bridge
