server:
  port: 8080

spring:
  profiles:
    active: local

  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/
      database: acal_v4

logging:
  logs:
    level.org.springframework.data.mongodb.core: INFO
  level:
    org:
      springframework:
        data: DEBUG
